edition = "2018"
format_code_in_doc_comments = true
format_macro_matchers = true
group_imports = "StdExternalCrate"
imports_granularity = "Module"
imports_layout = "HorizontalVertical"
match_block_trailing_comma = true
reorder_impl_items = true
unstable_features = true
use_field_init_shorthand = true
wrap_comments = true
